image: java:8-jdk
stages:
 - build
 - test
 - deploy

before_script:
    - wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - tar -xvf apache-maven-3.6.3-bin.tar.gz
    - M2_HOME='./apache-maven-3.6.3'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    
build:
  stage: build
  script:
    - mvn install
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  script:
    - mvn test
  tags:
    - dalfcs_gitlab_docker_ci
